services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "toor"]
    volumes:
      - redis-data:/data
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data
    
volumes:
  redis-data:
  postgres-data: